"""
openclaw/backend/search/chroma_store.py

ChromaDB wrapper — persistent local vector store.

Design:
  - One ChromaDB collection: "openclaw_documents"
  - Each chunk stored as a document with metadata:
      doc_id, version_id, version_number, chunk_index, page_hint,
      doc_name, category, filename
  - IDs: "{version_id}_{chunk_index}"  — unique per chunk
  - Embeddings: generated by Mistral embed API (mistral-embed model)
  - On re-index: delete old chunks for version_id, insert new ones

Storage location: ./chroma_db/  (persistent on disk between restarts)
"""
import logging
from functools import lru_cache
from pathlib import Path
from typing import Any

logger = logging.getLogger("openclaw.search.chroma")

CHROMA_DIR  = Path("./chroma_db")
COLLECTION  = "openclaw_documents"
EMBED_MODEL = "mistral-embed"
EMBED_DIM   = 1024   # mistral-embed output dimension


# ── Singleton client ──────────────────────────────────────────────────────────

@lru_cache(maxsize=1)
def _get_client():
    import chromadb
    CHROMA_DIR.mkdir(exist_ok=True)
    client = chromadb.PersistentClient(path=str(CHROMA_DIR))
    logger.info(f"[chroma] Persistent client initialised at {CHROMA_DIR}")
    return client


def get_collection():
    """Return (or create) the single OpenClaw collection."""
    client = _get_client()
    return client.get_or_create_collection(
        name=COLLECTION,
        metadata={"hnsw:space": "cosine"},   # cosine similarity
    )


# ── Embedding ─────────────────────────────────────────────────────────────────

def embed_texts(texts: list[str], api_key: str) -> list[list[float]]:
    """
    Embed a batch of texts using Mistral embed API.
    Returns list of embedding vectors (one per text).
    Falls back to zero vectors on API failure so indexing never hard-blocks.
    """
    if not texts:
        return []
    if not api_key:
        logger.warning("[chroma] No MISTRAL_API_KEY — returning zero embeddings")
        return [[0.0] * EMBED_DIM for _ in texts]

    try:
        from mistralai import Mistral
        client   = Mistral(api_key=api_key)
        response = client.embeddings.create(model=EMBED_MODEL, inputs=texts)
        return [item.embedding for item in response.data]
    except Exception as exc:
        logger.error(f"[chroma] Embedding failed: {exc}")
        return [[0.0] * EMBED_DIM for _ in texts]


# ── Index a document version ──────────────────────────────────────────────────

def index_version(
    version_id:     int,
    doc_id:         int,
    version_number: int,
    doc_name:       str,
    category:       str,
    filename:       str,
    chunks,          # list[Chunk] from chunker
    api_key:        str,
) -> int:
    """
    Index all chunks for a document version into ChromaDB.
    Deletes any existing chunks for this version_id first (re-index safe).
    Returns number of chunks indexed.
    """
    if not chunks:
        logger.info(f"[chroma] No chunks for version_id={version_id} — skipping")
        return 0

    collection = get_collection()

    # ── Delete existing chunks for this version ───────────────────────────────
    delete_version(version_id)

    # ── Prepare batch ─────────────────────────────────────────────────────────
    ids       = [f"{version_id}_{c.chunk_index}" for c in chunks]
    documents = [c.text for c in chunks]
    metadatas = [
        {
            "doc_id":         doc_id,
            "version_id":     version_id,
            "version_number": version_number,
            "chunk_index":    c.chunk_index,
            "page_hint":      c.page_hint or 0,
            "doc_name":       doc_name,
            "category":       category,
            "filename":       filename,
        }
        for c in chunks
    ]

    # ── Embed in batches of 32 (Mistral rate-limit safe) ──────────────────────
    BATCH = 32
    all_embeddings: list[list[float]] = []
    for i in range(0, len(documents), BATCH):
        batch_embeddings = embed_texts(documents[i:i+BATCH], api_key)
        all_embeddings.extend(batch_embeddings)

    # ── Upsert into ChromaDB ──────────────────────────────────────────────────
    collection.upsert(
        ids=ids,
        documents=documents,
        embeddings=all_embeddings,
        metadatas=metadatas,
    )

    logger.info(f"[chroma] Indexed {len(chunks)} chunk(s) for version_id={version_id} doc='{doc_name}'")
    return len(chunks)


# ── Delete ────────────────────────────────────────────────────────────────────

def delete_version(version_id: int) -> None:
    """Remove all chunks for a specific version from ChromaDB."""
    try:
        collection = get_collection()
        existing   = collection.get(where={"version_id": version_id})
        if existing["ids"]:
            collection.delete(ids=existing["ids"])
            logger.info(f"[chroma] Deleted {len(existing['ids'])} chunk(s) for version_id={version_id}")
    except Exception as exc:
        logger.warning(f"[chroma] Delete failed for version_id={version_id}: {exc}")


def delete_document(doc_id: int) -> None:
    """Remove all chunks for all versions of a document."""
    try:
        collection = get_collection()
        existing   = collection.get(where={"doc_id": doc_id})
        if existing["ids"]:
            collection.delete(ids=existing["ids"])
            logger.info(f"[chroma] Deleted {len(existing['ids'])} chunk(s) for doc_id={doc_id}")
    except Exception as exc:
        logger.warning(f"[chroma] Delete failed for doc_id={doc_id}: {exc}")


# ── Query ─────────────────────────────────────────────────────────────────────

def search(
    query:       str,
    api_key:     str,
    n_results:   int = 8,
    category:    str | None = None,
    doc_id:      int | None = None,
    version_id:  int | None = None,
) -> list[dict]:
    """
    Semantic search over indexed chunks.

    Filters:
      category   — restrict to a document category
      doc_id     — restrict to a specific document (all versions)
      version_id — restrict to one specific version

    Returns list of result dicts:
      { text, score, doc_id, doc_name, version_number, filename, category, chunk_index, page_hint }
    """
    if not query.strip():
        return []

    query_embedding = embed_texts([query], api_key)
    if not query_embedding or all(v == 0 for v in query_embedding[0]):
        logger.warning("[chroma] Zero query embedding — semantic search unavailable")
        return []

    # Build where clause
    where: dict[str, Any] = {}
    if version_id is not None:
        where = {"version_id": version_id}
    elif doc_id is not None:
        where = {"doc_id": doc_id}
    elif category:
        where = {"category": category}

    try:
        collection = get_collection()
        results    = collection.query(
            query_embeddings=query_embedding,
            n_results=min(n_results, max(collection.count(), 1)),
            where=where if where else None,
            include=["documents", "metadatas", "distances"],
        )
    except Exception as exc:
        logger.error(f"[chroma] Query failed: {exc}")
        return []

    output = []
    ids_list   = results.get("ids",        [[]])[0]
    docs_list  = results.get("documents",  [[]])[0]
    metas_list = results.get("metadatas",  [[]])[0]
    dists_list = results.get("distances",  [[]])[0]

    for chunk_id, doc_text, meta, distance in zip(ids_list, docs_list, metas_list, dists_list):
        # Cosine distance → similarity score (0-1, higher = more similar)
        score = round(1 - distance, 4)
        output.append({
            "chunk_id":      chunk_id,
            "text":          doc_text,
            "score":         score,
            "doc_id":        meta.get("doc_id"),
            "version_id":    meta.get("version_id"),
            "doc_name":      meta.get("doc_name", ""),
            "version_number":meta.get("version_number", 1),
            "filename":      meta.get("filename", ""),
            "category":      meta.get("category", ""),
            "chunk_index":   meta.get("chunk_index", 0),
            "page_hint":     meta.get("page_hint", 0) or None,
        })

    # Sort by score descending
    return sorted(output, key=lambda r: r["score"], reverse=True)


# ── Stats ─────────────────────────────────────────────────────────────────────

def collection_stats() -> dict:
    """Return basic stats about the ChromaDB collection."""
    try:
        collection = get_collection()
        count      = collection.count()
        return {"total_chunks": count, "collection": COLLECTION, "storage": str(CHROMA_DIR)}
    except Exception as exc:
        return {"error": str(exc)}
